#!/usr/bin/env python

import os
import sys
import subprocess

try:
	user = 'root'
	host, port = open (os.path.join (os.path.expanduser ('~'),
		'.meego-scp-rc')).read ().split (':', 1)
except:
	print 'meego-scp has not been configured. Run meego-scp-setup first.'
	sys.exit (1)

process_self_args = True
user = 'root'
set_user = False
scp_args_left = []
scp_arg_right = sys.argv[-1]
if scp_arg_right == sys.argv[0]:
	scp_arg_right = ''

for arg in sys.argv[1:-1]:
	if process_self_args and arg == '--':
		process_self_args = False
	elif process_self_args and arg == '-u':
		set_user = True
	elif set_user:
		set_user = False
		user = arg
	else:
		scp_args_left.append (arg)

command = ['scp', '-P', port]
[command.append (arg) for arg in scp_args_left]
command.append ('%s@%s%s' % (user, host, scp_arg_right))
print command
sys.exit (subprocess.call (command))
